when:
 - event: [ push, tag ]
   branch: main

steps:
 - name: build
   image: python:3-alpine
   commands:
    - python3 -m pip install --upgrade build
    - python3 -m build

 - name: publish
   when:
    - event: tag
   image: python:3-alpine
   commands:
    - python3 -m pip install twine
    - python3 -m twine upload --repository testpypi dist/*
   environment:
     TWINE_PASSWORD:
       from_secret: pypi-token