when:
 - event: push
   branch: main

steps:
 - name: build
   image: python:3-alpine
   commands:
    - python3 -m pip install --upgrade build
	- python3 -m build

 - name: publish
   image: gitea.elara.ws/music-kraken/plugin-twine
   settings:
     repository_url: "https://test.pypi.org"
     username: __token__
     password:
       from_secret: pypi-token